baseURL = "https://rustinblockchain.org/"
languageCode = "en-us"
title = "Rust in Blockchain"
theme = "mainroad"
paginate = "6" # Number of posts per page
disqusShortname = "rustinblockchain" # Enable Disqus comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id
publishDir = "docs"

[Params]
  subtitle = "Bringing engineering insight and experience to blockchain technology." # Subtitle of your site. Used in site header
  description = "A monthly newsletter for Rust and blockchain developers." # Site description. Used in meta description
  copyright = "Rust in Blockchain" # Footer copyright holder, otherwise will use site title
  opengraph = true # Enable OpenGraph if true
  twitter_cards = true # Enable Twitter Cards if true
  readmore = false # Show "Read more" button in list if true
  authorbox = false # Show authorbox at bottom of pages if true
  post_navigation = true # Show post navigation at bottom of pages if true
  post_meta = ["date", "categories"] # Order of post meta information
  mainSections = ["newsletters", "blogposts"] # Specify section pages to show on home page and the "Recent articles" widget
  dateformat = "January 02, 2006"
  mathjax = true # Enable MathJax
  mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # Specify MathJax path
  mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config
  highlightColor = "#e22d30" # Override highlight color
  customCSS = ["css/custom.css"] # Include custom CSS files
  customJS = ["js/custom.js"] # Include custom JS files
  enableEmoji = true
  enableGitInfo = false

[menu]
  [[menu.main]]
    identifier = "newsletters"
    name = "newsletters"
    pre = "<i class='fa fa-road'></i>"
    url = "/newsletters"
    weight = -110

  [[menu.main]]
    identifier = "blogposts"
    name = "blogposts"
    pre = "<i class='fa fa-road'></i>"
    url = "/blogposts"
    weight = -100

  [[menu.main]]
    identifier = "about"
    name = "about us"
    pre = "<i class='fa fa-heart'></i>"
    url = "/about"
    weight = -90

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "right"  # Configure layout for list pages
  single = true # Configure layout for single pages
  # Enable widgets in given order
  widgets = [ "subscribe",  "social", "categories", "support"] #"search"

[Params.widgets.social]
  # Enable parts of social widget
  twitter = "rust_blockchain"
  telegram = "rustinblockchain"
  github = "rust-in-blockchain"
  email = "hello@rustinblockchain.org"
