baseURL = "https://rustinblockchain.org/"
languageCode = "en-us"
title = "Rust in Blockchain ❤ rib.rs"
theme = "mainroad"
paginate = "6"
# googleAnalytics = ""
publishDir = "../rust-in-blockchain.github.io"
relativeURLs = true

[Params]
  subtitle = "Bringing engineering insight and experience to blockchain technology." # Subtitle of your site. Used in site header
  description = "A monthly newsletter for Rust and blockchain developers." # Site description. Used in meta description
  copyright = "Rust in Blockchain" # Footer copyright holder, otherwise will use site title
  opengraph = true # Enable OpenGraph if true
  twitter_cards = true # Enable Twitter Cards if true
  readmore = false # Show "Read more" button in list if true
  authorbox = false # Show authorbox at bottom of pages if true
  pager = true # Show post navigation at bottom of pages if true
  post_meta = ["date", "categories"] # Order of post meta information
  mainSections = ["newsletters", "blogposts"] # Specify section pages to show on home page and the "Recent articles" widget
  dateformat = "January 02, 2006"
  mathjax = true # Enable MathJax
  mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # Specify MathJax path
  mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config
  highlightColor = "#e22d30" # Override highlight color
  customCSS = ["css/custom.css"] # Include custom CSS files
  customJS = ["js/custom.js"] # Include custom JS files
  enableEmoji = true
  enableGitInfo = true
  addThis = "ra-123456789ABCDEF"

[menu]
    [[menu.main]]
    identifier = "newsletters"
    name = "Newsletters"
    pre = "<i class='fa fa-road'></i>"
    url = "/newsletters"
    weight = -110

   [[menu.main]]
    identifier = "blogposts"
    name = "Blog Posts"
    pre = "<i class='fa fa-road'></i>"
    url = "/blogposts"
    weight = -100

  [[menu.main]]
    identifier = "awesome-rib"
    name = "Awesome RiB"
    pre = "<i class='fa fa-road'></i>"
    url = "/awesome-blockchain-rust"
    weight = -90

   [[menu.main]]
    identifier = "job-board"
    name = "Job Board"
    pre = "<i class='fa fa-road'></i>"
    url = "/job-board"
    weight = -80

  [[menu.main]]
    identifier = "learning"
    name = "Learning"
    pre = "<i class='fa fa-heart'></i>"
    url = "/learning"
    weight = -70

  [[menu.main]]
    identifier = "contributing"
    name = "Contributing"
    pre = "<i class='fa fa-heart'></i>"
    url = "/contributing"
    weight = -60

  [[menu.main]]
    identifier = "about"
    name = "About Us"
    pre = "<i class='fa fa-heart'></i>"
    url = "/about"
    weight = -50

  [[menu.main]]
    identifier = "RSS"
    name = "RSS"
    pre = "<i class='fa fa-heart'></i>"
    url = "/index.xml"
    weight = -40

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "right"  # Configure layout for list pages
  single = true # Configure layout for single pages
  # Enable widgets in given order
  widgets = [ "subscribe", "support", "social"] #"search"

[Params.widgets.social]
  # Enable parts of social widget
  twitter = "rust_blockchain"
  telegram = "rustinblockchain"
  github = "rust-in-blockchain"
  email = "hi@rib.rs"
